### ISSUE TITLE
Create a secondary, low bitrate RTMP stream

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-devops#12]

**Comment by marcoherbst** [comment]
@mosic is this issue in the wrong place?

**Comment by mosic** [comment]
@marcoherbst No, the nginx-rtmp configuration is in this repo.

**Comment by mosic** [comment]
On the second thought we can just keep the issue in evercam-media, as that's where the stream will be initiated from. https://github.com/evercam/evercam-media/issues/99#issuecomment-215367158
