### ISSUE TITLE
Setup Nginx log rotation

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-devops#22]

**Comment by ijunaid8088** [comment]
https://www.digitalocean.com/community/tutorials/how-to-configure-logging-and-log-rotation-in-nginx-on-an-ubuntu-vps quite relevant!

**Comment by ijunaid8989** [comment]
Log Rotation:

When your application is making so many logs in one file, and your log file is getting so huge, that you cannot able to find anything related to errors in it, then you use logs rotation.

For our Ngnix it was enabled. I have added it to a script as. 

path:  /etc/logrotate.d/nginx` (logrotate is a default application in Ubuntu).

```
/var/log/nginx/*.log {
        daily
        missingok
        rotate 10
        compress
        delaycompress
        notifempty
        create 0644 nginx nginx
        sharedscripts
        postrotate
                [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
        endscript
}
```
- create: This creates a new log file and set the permission 644 with the ownership nginx.
- daily: ensures daily rotation
- rotate 10: Save 10 copies of the log file.
- missingok: Don't output the error if logfile is missing.
- notifempty: Don't rotate log file if it is empty.
- compress: Compress the old copies of log files with gzip(1) by default
- sharedscripts: This makes the scripts to run once, no matter how many logs match the wildcarded pattern, and the whole pattern is passed to them.

Now it will gzip the old log file, and keep 10 days history as well.

(We already have done this for Evercam Server log.)
