### ISSUE TITLE
ibrowse compilation error

### ISSUE THREAD

**Issue by eugenehp** [evercam/evercam-devops#26]
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/evercam-media$ mix deps.compile ibrowse
==> ibrowse (compile)
Compiling src/ibrowse_lib.erl failed:
src/ibrowse_lib.erl:371: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
ERROR: compile failed while processing /vagrant/evercam-media/deps/ibrowse: rebar_abort
** (Mix) Could not compile dependency ibrowse, /home/vagrant/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile ibrowse
```

<img width="1550" alt="screen shot 2015-10-13 at 14 05 18" src="https://cloud.githubusercontent.com/assets/1857263/10454236/813f6546-71b3-11e5-86d4-b0bdbd1d4c57.png">

**Comment by eugenehp** [comment]
Fixed [here](https://github.com/evercam/evercam-media/commit/dd7ff62f0fa4f53573556887a407f9f6407c408b)

<img width="1550" alt="screen shot 2015-10-13 at 14 12 51" src="https://cloud.githubusercontent.com/assets/1857263/10454374/8ccd278a-71b4-11e5-823a-a09ca1751653.png">

**Comment by mosic** [comment]
:+1:
