### ISSUE TITLE
Loading camera vendors and models

### ISSUE THREAD

**Issue by entone** [evercam/evercam-devops#3]
I attempted to load the vendor and model data for the API using `rake import_vendor_data` and `rake  import_cambase_data` the first required some work-arounds to avoid an AWS key error, and than failed immediately.

The second method appeared to work, but no data was available in the dashboard when adding a new camera.

**Comment by mosic** [comment]
Hi, thanks for reaching out. Those rake tasks were made before we went open source, so they're assuming that the developer has access to the file on S3 were the model data is stored.

Right now we're in the middle of importing additional data to the API (you can see it on `add_extra_data` branch), when that gets merged we will modify the tasks so everyone has access to the vendor and model data. You can expect that to happen during next week.

As a temporary workaround, running the dashboard without `EVERCAM_LOCAL=true` will use the `api.evercam.io` as the API server so you'll have access to all vendor and model data we have in production.

**Comment by entone** [comment]
I was able to pull down the csv file, it is publicly accessible, however the rake task failed. I don't have the specific error in front of me unfortunately.

**Comment by ijunaid8088** [comment]
As first we don't use API.evercam.io anymore. And secondly, the vendor model data of production is available to everyone in evercam-server.
