### ISSUE TITLE
Configure Upstart service for evercam-media properly

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-devops#34]
Starting an exrm release in Upstart using `start` causes Upstart to track the wrong pid, rendering it useless. Currently this is "fixed" by a hack which watches over the processes existance of `beam` and starts one if it doesn't exist.

This can be fixed by using `foreground` instead, directing logs from stdout/stderr to upstart and configuring logs collector to use Upstart log dir.

**Comment by marcoherbst** [comment]
@azharmalik3 you're aware of this?

**Comment by ijunaid8088** [comment]
@marcoherbst we have moved to higher version of Ubuntu on which Upstart isn't supported. Now we are going to use Systemd, which are service units. But Somehow this can be a point for service unit as well.

**Comment by ijunaid8989** [comment]
Its done with the update of Ubuntu version.
