### ISSUE TITLE
Dependency error in evercam-ruby

### ISSUE THREAD

**Issue by alex-fernandez** [evercam/evercam-devops#35]
Had any experience this on there end? 

Could not find a valid gem 'vendor/cache/evercam_misc-0.0.10.gem' (>= 0) in any repository

**Comment by mosic** [comment]
Hi Alex. That doesn't happen for me, and evercam-misc is still available on GitHub: https://github.com/evercam/evercam-misc. We avoid these kinds of issues in evercam-api by vendoring all dependencies.

Btw this might not be a good time to get involved as we're currently transitioning our main application (and it's dependencies) from Ruby to Elixir.

**Comment by alex-fernandez** [comment]
@mosic , I would like to dockerize the app, so it would be easy for deployment.

**Comment by mosic** [comment]
@alex-fernandez Ok, have you tried using (or looked at) the Ansible playbooks in this repository to provision Docker images? That's what we use for Vagrant machines.

Aside from that I'm not sure I can help, as I haven't used Docker personally.

**Comment by ijunaid8989** [comment]
Not relevant, We never dockerize devops, anyhow we have merged this repo https://github.com/evercam/evercam-misc in our main ruby applications directly (admin/dash).
