### ISSUE TITLE
RAID Monitoring

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-devops#40]
From a quick google, my favourite option is:
https://www.lowendtalk.com/discussion/11758/lsi-megaraid-email-alerts  but using, as the first commenter says, http://www.logix.cz/michal/devel/smtp-cli/

Next I would have looked at a hosted SNMP monitoring solution:
http://www.monitis.com/support/server-device-monitoring/snmp-monitoring
https://www.uptrends.com/products/server-monitoring/snmp-monitoring
https://anturis.com/monitors/snmp-monitor/

Or, we setup our own vserver again:
https://www.opennms.org/en
Zabbix
Nagios Core https://www.nagios.com/solutions/snmp-monitoring/

Or get more creative:
https://www.robustperception.io/snmp-monitoring-with-prometheus/

Or build our own:
https://ernie.io/2014/07/10/snmp-in-elixir/

I also see some efforts of people who have added SNMP monitoring to New Relic.

**Comment by marcoherbst** [comment]
Also worth a mention, but I dont understand at all what it does and my guess is that it's similar to the first suggestion above: http://hwraid.le-vert.net/

**Comment by ijunaid8989** [comment]
FYI
Building it on our own is a fancy idea, but I had talked to Ernie Miller in past, He didn't have so many positive thoughts on SNMP in elixir as a next step to what he has already done.

**Comment by ijunaid8989** [comment]
There is a quite easy and possible solution for this is:

As we already know our RAID or all servers is MegaRaid, and We have already installed MegaCli, on each server, which Actually Nagios was using to get the results,

So What We can do is: Using our Elixir Application (EdgeCommander), use the credentials of server, and just run the command, such as 

Results of a command ran on SeaweedFS master server, but from EdgeCommander Console.
```
iex(5)> res = SSHEx.cmd! conn, '/opt/MegaRAID/MegaCli/MegaCli64 -AdpAllInfo -aALL | grep "Degraded"'    
"  Degraded        : 0 \n"
iex(6)> res = SSHEx.cmd! conn, '/opt/MegaRAID/MegaCli/MegaCli64 -AdpAllInfo -aALL | grep "Failed"'  
"Security Key Failed              : No\n  Failed Disks    : 0 \nDeny Force Failed                       : No\n"
```
using https://github.com/rubencaro/sshex, It will solve all the issue for us.

its kind of monitoring, that, run the command after the asked frequency, and then In case of Failure, get an email, through this, we can achieve all that we were doing with Nagios, the actual purpose of Nagios was also to get the access to the main server and run the command through NRPE, and before that we had to install/setup MegaCLI to our servers.

We can have a report, for adding server's and enabling disabling MegaRaid on them, also the same way for the email alerts.
also then we can have as many commands as we need https://blog.frehi.be/2011/09/12/megacli-useful-commands/ to run on the server and get the result and monitor.

@marcoherbst what do you think about this? First and for most benefit is that there will be no expiry of the trail and we don't have to switch forth and back.

**Comment by marcoherbst** [comment]
@ijunaid8989 ... this is done, right? Could you do a quick check that you have it working and installed on all servers and then close  this issue?

**Comment by ijunaid8989** [comment]
@marcoherbst Its half done. For MegaRAID Controllers it's working..

After November we have 2 new servers which don't use MegaRAID anymore, they are on Adaptec hardware raid controller. 

I mostly check each server after a week, (Automated system is working as well) for Mega and Adaptec both.

So there is some changes need to be made on EC for Adaptec Controller, after that  I will close this issue.

**Comment by ijunaid8989** [comment]
It's done. 

Now [Edge Commander](https://github.com/EdgeCommander/edge-commander/commit/bfb9a424a224eed539b02edc63daf75c8dd3eba6) supports for both MegaRaid and Adaptec RAID as well. :boom:
